name: Develop Server CD

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/develop.key
          chmod 600 ~/.ssh/develop.key
          cat >>~/.ssh/config <<END
          Host develop
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/develop.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.DEV_HOSTNAME }}
          SSH_USER: ${{ secrets.DEV_USERNAME }}
          SSH_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
      - uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            server/package.json
      - name: Checkout and Pull origin
        run: ssh develop 'cd ~/store-4 && git checkout develop && git pull origin'
      
      - name: if changed dependencies, install dependencies 
        run: ssh develop 'cd ~/store-4/server && npm i'
        if: env.GIT_MATCHED_FILES

      - name: Reload Pm2
        run: ssh develop 'cd ~/store-4/server && npm run build && sudo pm2 reload store-4'
        
        
