name: Develop Server CD

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/develop.key
          chmod 600 ~/.ssh/develop.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/develop.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.DEV_HOSTNAME }}
          SSH_USER: ${{ secrets.DEV_USERNAME }}
          SSH_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
      - name: Nodejs Server
        run: ssh dev 'cd ~/store-4 && git checkout develop && git pull origin develop && cd server && npm i'
          
